# Generated by Django 5.2.1 on 2025-06-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ssn',
            field=models.CharField(default='0000', max_length=4, verbose_name='last 4 numbers of social security number'),
        ),
    ]
